name:        css-text
version:     0.1.2.2
synopsis:    CSS parser and renderer.
description: Please see the README and generated docs at <https://www.stackage.org/package/css-text>
category:    Web, Yesod
author:      Michael Snoyman <michael@snoyman.com>
maintainer:  Michael Snoyman <michael@snoyman.com>, Greg Weber <greg@gregweber.info>
license:     MIT
github:      yesodweb/css-text.git
stability:   Stable

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >=4 && <5
- text >=0.11
- attoparsec >=0.10.2.0

library:
  source-dirs: src
  ghc-options: -Wall
  when:
  - condition: ! '!(impl(ghc >=8.0))'
    dependencies:
    - semigroups >=0.16.1

tests:
  runtests:
    main: runtests.hs
    source-dirs: test
    dependencies:
    - hspec >=1.3
    - QuickCheck
    - css-text
